In [1]:
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# BigFrames Multimodal DataFrame

<table align="left">

  <td>
    <a href="https://colab.research.google.com/github/googleapis/python-bigquery-dataframes/blob/main/notebooks/multimodal/multimodal_dataframe.ipynb">
      <img src="https://raw.githubusercontent.com/googleapis/python-bigquery-dataframes/refs/heads/main/third_party/logo/colab-logo.png" alt="Colab logo"> Run in Colab
    </a>
  </td>
  <td>
    <a href="https://github.com/googleapis/python-bigquery-dataframes/blob/main/notebooks/multimodal/multimodal_dataframe.ipynb">
      <img src="https://raw.githubusercontent.com/googleapis/python-bigquery-dataframes/refs/heads/main/third_party/logo/github-logo.png" width="32" alt="GitHub logo">
      View on GitHub
    </a>
  </td>
  <td>
    <a href="https://console.cloud.google.com/bigquery/import?url=https://github.com/googleapis/python-bigquery-dataframes/blob/main/notebooks/multimodal/multimodal_dataframe.ipynb">
      <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTW1gvOovVlbZAIZylUtf5Iu8-693qS1w5NJw&s" alt="BQ logo" width="35">
      Open in BQ Studio
    </a>
  </td>
</table>

This notebook is introducing BigFrames Multimodal features:
1. Create Multimodal DataFrame
2. Combine unstructured data with structured data
3. Conduct image transformations
4. Use LLM models to ask questions and generate embeddings on images
5. PDF chunking function
6. Transcribe audio
7. Extract EXIF metadata from images

### Setup

Install the latest bigframes package if bigframes version < 2.4.0

In [2]:
# !pip install bigframes --upgrade

In [3]:
PROJECT = "bigframes-dev" # replace with your project.
# Refer to https://cloud.google.com/bigquery/docs/multimodal-data-dataframes-tutorial#required_roles for your required permissions

LOCATION = "us" # replace with your location.

# Dataset where the UDF will be created.
DATASET_ID = "bigframes_samples" # replace with your dataset ID.

OUTPUT_BUCKET = "bigframes_blob_test" # replace with your GCS bucket.
# The connection (or bigframes-default-connection of the project) must have read/write permission to the bucket.
# Refer to https://cloud.google.com/bigquery/docs/multimodal-data-dataframes-tutorial#grant-permissions for setting up connection service account permissions.
# In this Notebook it uses bigframes-default-connection by default. You can also bring in your own connections in each method.

import bigframes
# Setup project
bigframes.options.bigquery.project = PROJECT
bigframes.options.bigquery.location = LOCATION

# Display options
bigframes.options.display.blob_display_width = 300
bigframes.options.display.progress_bar = None

import bigframes.pandas as bpd
import bigframes.bigquery as bbq

In [4]:
import bigframes.bigquery as bbq

def get_runtime_json_str(series, mode="R", with_metadata=False):
    """
    Get the runtime (contains signed URL to access gcs data) and apply the
    ToJSONSTring transformation.

    Args:
        series: bigframes.series.Series to operate on.
        mode: "R" for read, "RW" for read/write.
        with_metadata: Whether to fetch and include blob metadata.
    """
    # 1. Optionally fetch metadata
    s = (
        bbq.obj.fetch_metadata(series)
        if with_metadata
        else series
    )

    # 2. Retrieve the access URL runtime object
    runtime = bbq.obj.get_access_url(s, mode=mode)

    # 3. Convert the runtime object to a JSON string
    return bbq.to_json_string(runtime)

def get_metadata(series):
    # Fetch metadata and extract GCS metadata from the details JSON field
    metadata_obj = bbq.obj.fetch_metadata(series)
    return bbq.json_query(metadata_obj.struct.field("details"), "$.gcs_metadata")

def get_content_type(series):
    return bbq.json_value(get_metadata(series), "$.content_type")

def get_size(series):
    return bbq.json_value(get_metadata(series), "$.size").astype("Int64")

def get_updated(series):
    return bpd.to_datetime(bbq.json_value(get_metadata(series), "$.updated").astype("Int64"), unit="us", utc=True)

### 1. Create Multimodal DataFrame
There are several ways to create Multimodal DataFrame. The easiest way is from the wildcard paths.

In [5]:
# Create blob columns from wildcard path.
df_image = bpd.from_glob_path(
    "gs://cloud-samples-data/bigquery/tutorials/cymbal-pets/images/*", name="image"
)

In [6]:
# Take only the 5 images to deal with. Preview the content of the Mutimodal DataFrame
df_image = df_image.head(5)
df_image

/usr/local/lib/python3.12/dist-packages/bigframes/dtypes.py:987: JSONDtypeWarning: JSON columns will be represented as pandas.ArrowDtype(pyarrow.json_())
instead of using `db_dtypes` in the future when available in pandas
(https://github.com/pandas-dev/pandas/issues/60958) and pyarrow.
  warnings.warn(msg, bigframes.exceptions.JSONDtypeWarning)
/usr/local/lib/python3.12/dist-packages/bigframes/core/logging/log_adapter.py:229: ApiDeprecationWarning: The blob accessor is deprecated and will be removed in a future release. Use bigframes.bigquery.obj functions instead.
  return prop(*args, **kwargs)

                                               image
0  {"access_urls":{"expiry_time":"2026-02-26T23:5...
1  {"access_urls":{"expiry_time":"2026-02-26T23:5...
2  {"access_urls":{"expiry_time":"2026-02-26T23:5...
3  {"access_urls":{"expiry_time":"2026-02-26T23:5...
4  {"access_urls":{"expiry_time":"2026-02-26T23:5...

[5 rows x 1 columns]

### 2. Combine unstructured data with structured data

Now you can put more information into the table to describe the files. Such as author info from inputs, or other metadata from the gcs object itself.

In [7]:
# Combine unstructured data with structured data
df_image = df_image.head(5)
df_image["author"] = ["alice", "bob", "bob", "alice", "bob"]  # type: ignore
df_image["content_type"] = get_content_type(df_image["image"])
df_image["size"] = get_size(df_image["image"])
df_image["updated"] = get_updated(df_image["image"])
df_image

/usr/local/lib/python3.12/dist-packages/bigframes/dtypes.py:987: JSONDtypeWarning: JSON columns will be represented as pandas.ArrowDtype(pyarrow.json_())
instead of using `db_dtypes` in the future when available in pandas
(https://github.com/pandas-dev/pandas/issues/60958) and pyarrow.
  warnings.warn(msg, bigframes.exceptions.JSONDtypeWarning)
/usr/local/lib/python3.12/dist-packages/bigframes/core/logging/log_adapter.py:229: ApiDeprecationWarning: The blob accessor is deprecated and will be removed in a future release. Use bigframes.bigquery.obj functions instead.
  return prop(*args, **kwargs)

,image,author,content_type,size,updated
0,"<img src=""https://storage.googleapis.com/cloud-samples-data/bigquery%2Ftutorials%2Fcymbal-pets%2Fimages%2Fk9-guard-dog-paw-balm.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20260226%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20260226T175138Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1742492703986347&X-Goog-Signature=2c99496f84bb4024a1575e9c431c309769b0e6c1c674bdcbe55a02d6d9a4b22e0ac0b601860e9741ed50da64cf3ae823d21e595661261b67e11b2431007bed70156a973fd5a50ba61b4047c5c26bc00d2c777f28cd54adeb9ec971274ace50ddc53ec2b270503c779f746c879d542de96e21c97aac6a61b4dba9b77b717653e38a7c00c5c75bf8ac252d1fb8b28b9a43ea9ec59d52c98fb614f04d508de0d9f1eeb6f495c303035dba664ebc639c6b155f0034563362878464c2675786e0cf829fe99e21e19ef505325f17474119aae83eab95f000e4c99f54c3b821a12c0f24d65f869ff3bd470bfb4208579f46b05b52d6aabb6306f90d8e3c65d25ddfca03"" width=""300"">",alice,image/png,1591240,2025-03-20 17:45:04+00:00
1,"<img src=""https://storage.googleapis.com/cloud-samples-data/bigquery%2Ftutorials%2Fcymbal-pets%2Fimages%2Fk9-guard-dog-hot-spot-spray.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20260226%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20260226T175138Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1742492702954473&X-Goog-Signature=4f5da51b26b7d7a88d621b2ec6f1deb55c65729b66e652cef4ab83072dfbac94764ef1a0bbd0ed4ff2e4e2d424b7961798e97e7c283b8bcc4f96276d90ccbdd2724ca7641f0c1c2b6134a1e5ebf32af05508a8d69ecc5bcc3024bf4932f9961daa317ea4af634dbcef20f81491172564fe19c5009b9d7a1b13e45e5cc17446f041505ea56ca70deffb16486e3e750f5622ac873d8404918542fc86b39ae7c18f8638884150779c07586cfc8c72982ebc470f1534d99e53fe831dcf0595e5455c91ad46e9db5ed84291b9bdfc747bfd67eaeb89819fcb72bdadf5e3b611b089cf8483d7bba504a104b2ec9c971d388cb017950b4d2b2b4ccc24c750d7540fbd69"" width=""300"">",bob,image/png,1182951,2025-03-20 17:45:02+00:00
2,"<img src=""https://storage.googleapis.com/cloud-samples-data/bigquery%2Ftutorials%2Fcymbal-pets%2Fimages%2Ffluffy-buns-chinchilla-food-variety-pack.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20260226%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20260226T175138Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1742492694988945&X-Goog-Signature=59eebb62bad350191604c8efe234715164a189a083dcaf8f775c9a2329d7ed7d261a1c0144fe8ece66da71c96a7937d543131730813f54ad97a7413695a1f021b4500909d2b987c399c463541b72b1130d4671424a25b79d082030ee1eaa1681bd73a008f5043aeb6ba3d91b1389534056ffce4142f86817a1c630f3e83df7d294c9c2833f04eb4ddc04f4e65fb096bdcade43acf78ae9bb92adc78062b04099ef40342b615e96767d3742be826ddb16fdd46592d7abc1a2df255129244d5e1f52b4a70b1f3ebbc1a36598c9a59c5bf92bb7cd0578cab9d2e14228e378215a14a2123cf10726e61efe2e8bf83710c98793681206a2b4e6bb370fc3ae9c72ec74"" width=""300"">",bob,image/png,1520884,2025-03-20 17:44:55+00:00
3,"<img src=""https://storage.googleapis.com/cloud-samples-data/bigquery%2Ftutorials%2Fcymbal-pets%2Fimages%2Fpurrfect-perch-cat-scratcher.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20260226%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20260226T175138Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1742492719670724&X-Goog-Signature=45f332b202220ff522101102b1338621d64f64b568cf2fad01fc175b64f108de26a4d65742c37553209b8ab979029cb219acaf341ff0b5a16a80ab914f4fbac3997e8fa3d048db2eb8cfc2a5c4bbaa7aef594b0f93030c951fbed0758765f6fa958403bedf771302df8b8a49c3e40a4d4680e157944da26f06ed79979347a2b8e77d3fddb5b0179e79376ff1498697d3da6b6dca09952e3cc0bf388bca7e56ed13ac2356a86ac17ec6361f71a8aee63ea3970585d50946e9684156388a768e1a8ca8ec849bfe6513c1923e35a34c43c9a47e0793c2d7b6ec7c2eaa5f0f0b9598cbf8b80326407bbcd79933cbca23663ea6e74ee9f8f53caf27f40f1e49fe332b"" width=""300"">",alice,image/png,1235401,2025-03-20 17:45:19+00:00
4,"<img src=""https://storage.googleapis.com/cloud-samples-data/bigquery%2Ftutorials%2Fcymbal-pets%2Fimages%2Fchirpy-seed-deluxe-bird-food.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20260226%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20260226T175138Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1742492687196980&X-Goog-Signature=899c59de64f990083cbbfe14da898600a9821b003f6ae742f60d9f830acbbc42cdb759729a23dbd92cfdddfe881e2cafd9d1fa3efcab4d5126a9970bfd4839cf4073d9e1255f099be9202d744c18c13dc9a4109b8fb4970f7e4eeae90301560bf50fdd0ce39f76932663b3483d624799811be0c8b423054021aa058f50ffcf6092e8b3c0a7bb7332691d75c2d888edeaed4d1bcb88ff33bc4b6d737c12df6ed5299843bb4075406bd94c2b998d0233143c3338f415d583b48a7d80bc715197844cbb49b4f754297b8b6855139651b37bab23ec786c0a7a16c0b1284d0e4d1a8370ed11de4acbf894c41dff518f5e35f49bc240e954c7ef90127dcdc1e97c5346"" width=""300"">",bob,image/png,1591923,2025-03-20 17:44:47+00:00

### 3. Conduct image transformations

This section demonstrates how to perform image transformations like blur, resize, and normalize using custom BigQuery Python UDFs and the `opencv-python` library.

In [8]:
# Construct the canonical connection ID
FULL_CONNECTION_ID = f"{PROJECT}.{LOCATION}.bigframes-default-connection"

@bpd.udf(
    input_types=[str, str, int, int],
    output_type=str,
    dataset=DATASET_ID,
    name="image_blur",
    bigquery_connection=FULL_CONNECTION_ID,
    packages=["opencv-python", "numpy", "requests"],
)
def image_blur(src_rt: str, dst_rt: str, kx: int, ky: int) -> str:
    import json
    import cv2 as cv
    import numpy as np
    import requests
    import base64

    src_obj = json.loads(src_rt)
    src_url = src_obj["access_urls"]["read_url"]

    response = requests.get(src_url, timeout=30)
    response.raise_for_status()

    img = cv.imdecode(np.frombuffer(response.content, np.uint8), cv.IMREAD_UNCHANGED)
    if img is None:
        raise ValueError("cv.imdecode failed")

    kx, ky = int(kx), int(ky)
    img_blurred = cv.blur(img, ksize=(kx, ky))

    success, encoded = cv.imencode(".jpeg", img_blurred)
    if not success:
        raise ValueError("cv.imencode failed")

    # Handle two output modes
    if dst_rt:  # GCS/Series output mode
        dst_obj = json.loads(dst_rt)
        dst_url = dst_obj["access_urls"]["write_url"]

        requests.put(dst_url, data=encoded.tobytes(), headers={"Content-Type": "image/jpeg"}, timeout=30).raise_for_status()

        uri = dst_obj["objectref"]["uri"]
        return uri

    else:  # BigQuery bytes output mode
        image_bytes = encoded.tobytes()
        return base64.b64encode(image_bytes).decode()

def apply_transformation(series, dst_folder, udf, *args, verbose=False):
    import os
    dst_folder = os.path.join(dst_folder, "")
    # Fetch metadata to get the URI
    metadata = bbq.obj.fetch_metadata(series)
    current_uri = metadata.struct.field("uri")
    dst_uri = current_uri.str.replace(r"^.*\/(.*)$", rf"{dst_folder}\1", regex=True)
    dst_blob = dst_uri.str.to_blob(connection=FULL_CONNECTION_ID)
    df_transform = bpd.DataFrame({
        "src_rt": get_runtime_json_str(series, mode="R"),
        "dst_rt": get_runtime_json_str(dst_blob, mode="RW"),
    })
    res = df_transform[["src_rt", "dst_rt"]].apply(
        udf, axis=1, args=args
    )
    return res if verbose else res.str.to_blob(connection=FULL_CONNECTION_ID)

# Apply transformations
df_image["blurred"] = apply_transformation(
    df_image["image"], f"gs://{OUTPUT_BUCKET}/image_blur_transformed/",
    image_blur, 20, 20
)
df_image[["image", "blurred"]]

/usr/local/lib/python3.12/dist-packages/bigframes/pandas/__init__.py:151: PreviewWarning: udf is in preview.
  return global_session.with_default_session(
/usr/local/lib/python3.12/dist-packages/bigframes/dataframe.py:4735: FunctionAxisOnePreviewWarning: DataFrame.apply with parameter axis=1 scenario is in preview.
  warnings.warn(msg, category=bfe.FunctionAxisOnePreviewWarning)
/usr/local/lib/python3.12/dist-packages/bigframes/dtypes.py:987: JSONDtypeWarning: JSON columns will be represented as pandas.ArrowDtype(pyarrow.json_())
instead of using `db_dtypes` in the future when available in pandas
(https://github.com/pandas-dev/pandas/issues/60958) and pyarrow.
  warnings.warn(msg, bigframes.exceptions.JSONDtypeWarning)
/usr/local/lib/python3.12/dist-packages/bigframes/core/logging/log_adapter.py:229: ApiDeprecationWarning: The blob accessor is deprecated and will be removed in a future release. Use bigframes.bigquery.obj functions instead.
  return prop(*args, **kwargs)
/usr/local/lib/python3.12/dist-packages/bigframes/core/logging/log_adapter.py:229: ApiDeprecationWarning: The blob accessor is deprecated and will be removed in a future release. Use bigframes.bigquery.obj functions instead.
  return prop(*args, **kwargs)

,image,blurred
0,"<img src=""https://storage.googleapis.com/cloud-samples-data/bigquery%2Ftutorials%2Fcymbal-pets%2Fimages%2Fk9-guard-dog-paw-balm.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20260226%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20260226T175155Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1742492703986347&X-Goog-Signature=591cb8de22cf5f0e1c64314eac74fce41dc6faa563b19ced2def4cd2bb25183cde1d14d90cbfed3fada2762c725fffa65dd831dfd84d0643e85e9dd417cce99e26774f1c965ff7b39aa026d648a5f5f85c1f57d4c2a386ed366166e5c90038622ea6de285e3e709ce941682a5c3b972adf5f0e1c0a24b1d4c78d8c62d1d36dbbdc9ff0a909dafa7ebdaeb2cbb98e2bab5ad2faef1321ef45b63edc95d398973800b98dfa9cc2ee7649bb8e6bdd0c3dfff5df639c9a1a1aff0ba5f02215b245fc643ff1999d32073af19f6b63277eaa4f22f5045b2b8cba33b670ed04d5855bffdf9808acdacb557815a75827f61fdd3017298cd973736aaa27b1aee74798335c"" width=""300"">","<img src=""https://storage.googleapis.com/bigframes_blob_test/image_blur_transformed%2Fk9-guard-dog-paw-balm.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20260226%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20260226T175155Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1772128423699643&X-Goog-Signature=1554e1faa9e73f3979c86237e5a237fe674f0e474375893aa50256ab91fcaf8970a96de1636a9a07ba5a6de0b65f3017b0167e880751adc99aa2dd7b96cc74184f9264b611ef9ae5e71260a1865015721804fcf46d342e64ab648c54b5041fe927a2d04fac0866ac69d6a85ab35de354bedf88a0b284301163753ff37a48076c9811fbb2e90cdaefc80c38d308a1c544f640528c695684b92bf83597284e32bd60b7e2e023465615906490836c2dc6e6c44779e4e9cc4c22d0184c37ff27c350a7484150a4202d7bfe8644349ab3fd46fdd206608871414e9024704114e7585284bd031c26cc44781f49f194250feac0778b980dbff05a392b929cc71240c719"" width=""300"">"
1,"<img src=""https://storage.googleapis.com/cloud-samples-data/bigquery%2Ftutorials%2Fcymbal-pets%2Fimages%2Fk9-guard-dog-hot-spot-spray.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20260226%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20260226T175155Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1742492702954473&X-Goog-Signature=9bfc3ebc46660dbf6274807f62f782d71c85c04d2757681c5d9692c873dd3d5e16aeadb2b39b3ffcf5e786a5d821644b4d795b18b5c67e50595b46d5a2bb717328cae8501311571ee41ab2f60d6509fed1bedcbed785f4aac076bb3bf9c2f66656f4cf3d558abe99ccfeb59db1d12babb5072e3203441638effd1391032feade97997dbd2131aa536a4b40f2d063cca1b8d685d0668e3cebba1c5790a1a8c5ada78a31b73f66f3a86b118dd9309c6c86e4ed287a47049ee1ebe3e914a6f158ee3eed8ba063b33a6ceb6749f4e8f39dbbbe6699fea486983ae57a817d75a631515ea33115343ce82d4874ca142d34019cd48469c1938b49a8b976575d5174c81d"" width=""300"">","<img src=""https://storage.googleapis.com/bigframes_blob_test/image_blur_transformed%2Fk9-guard-dog-hot-spot-spray.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20260226%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20260226T175155Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1772128421381509&X-Goog-Signature=9cc748a04c61a084ec2c119df06be3c17d13df13797955f88ff75ad4b03f3642ef75ee722cfadff2b3b6b27049bad13d0859c32dd4ec9ab3927b7246a00a8ed8eb8c4ee1f7aacbf4b9f02bacfdcde677d4809d20afc44d28eec792b2386222d9d5d2c7e251687612ee7ea614b7371ecbf8e6d0fc1095777d85ee46aadfa2d6a10c459de8d0aea65c026bc5abdadedf09d60035aa5a95fa64d13a1c01a849ef870edc44eb98f4f8fbcfd721e9c594d18698b8cbcdbfe7566d6f422fc699c17582dd3081ad725945936487df63a05878df6bcba03afa4c898040c22ef0f5d5b6affbfe0a238876447bea2b2d903f2f2384a06f76a4841be39e412e06d2daf5fc2b"" width=""300"">"
2,"<img src=""https://storage.googleapis.com/cloud-samples-data/bigquery%2Ftutorials%2Fcymbal-pets%2Fimages%2Ffluffy-buns-chinchilla-food-variety-pack.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20260226%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20260226T175155Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1742492694988945&X-Goog-Signature=45300273e042540b6b621986842744ff7f733902d6bf28e229101a912a02f69105be192e14a81023098d3c0da7a130a5fcce19c3f128f12419c8ad7fb8d9f497cdbe216d921e553c0e3cc996f49d62e8766f6cd114fcd7fabbbc7ad109ee4609991370a3f4b7a6cf57600a903f79c4cd88740489d9e358c42942718c332e60fc2dfe1d1685e6f0528ed37fc697615e3316dd3765d4a21b7c867e1954a1f28ea752a0cc066edb992c2123869b67819b30875501527ecbb7f9db94364b181cd91fe09ded0dae58e28bd6ccb10d5ab2c85bf00880a2908fa63ae113bd3ce6cdce12ca12acd1f28d8971c4aa933522d713f64e15826d471b721b4aacf6073450ef9b"" width=""300"">","<img src=""https://storage.googleapis.com/bigframes_blob_test/image_blur_transformed%2Ffluffy-buns-chinchilla-food-variety-pack.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20260226%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20260226T175155Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1772128423603840&X-Goog-Signature=516d969f0c74a363a3b16a1a598fbbd6fd8faf00d15c9bb49b10f1108a807ca0b55a411243994e4b224c0398ebd081fd11892abace2ce80b6c1afc74f6acfc67fda6fd6b76893aaf55dd183623928544d4585b7436b4c0a5628acd1aab9492592110a1426b3b35fe999d51207a9eda38e26f1275fc2882571631a13a0b289fa290eb8bc3199f1538c02dbec4a17218fd0d99e6d4b766ef0b942ffd8690f9f031e5ce5289b24392adc546138962700ffa33cf913553302529b9a9d0b1ed7a9f6b0f36d0d15d5d4b081348619c0b90ad065f5d661f5991e673da7ae69f4e98d22838a3adf8f9784bbc51bfe8186b47237d0dec12097871600b77c17c71e885283b"" width=""300"">"
3,"<img src=""https://storage.googleapis.com/cloud-samples-data/bigquery%2Ftutorials%2Fcymbal-pets%2Fimages%2Fpurrfect-perch-cat-scratcher.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20260226%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20260226T175155Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1742492719670724&X-Goog-Signature=86368025bd6142cfc3cc9d2dc79781da8b521b7bbd819b1fe5cee27bffdd875a43cd13282e830ea0c76ac1538cae45f1b78126297f9103e7fa5ee6d0f423bb8be81ea915eb6f71ffcc89f411a53ab78320b57eb85b2f7f59adb624c284afdceed9e7057cf5dbf077f8acc153159d6c5ae5d049312c6e5bd41b5618ec7515af764d332bad607a0c90ea7f0493e18b74f2e05f9ffce27acf760fd2038df5963d60a2a98005e62f6cf24e8826a13dbf40440c95162d50ad4b5c049069f4967226519ae9806c972ebcccb509403cc24250ec289bac7a653526d77754f4394f07a793c358db08aba3d4d423256603cc3eb9f155ce9dc3a6328c1d1ccef1e884ff37aa"" width=""300"">","<img src=""https://storage.googleapis.com/bigframes_blob_test/image_blur_transformed%2Fpurrfect-perch-cat-scratcher.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20260226%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20260226T175155Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1772128421408907&X-Goog-Signature=36de4f746c9656d8b5e67ed3edd9127c18085c38f094a3bfaffa2ab58d1975d1fa572c766ae4518b05224ae75bf2cf61f4701a2d0d89ef01a1ac03102509584c34b1b893698a7d9db5cd926990dc3662cbe6b83bc9683e8f3507ee49db8f076f36953abce32d2c057ebe2f2d021ef2c7584379b8f04327b5a256d5f3f11ac8b66d9bf7d7937f9785edfb72097632c0c666264a1438cb6b6860bf26f088b742637d550711a37cd77eee64a81ff7eae916a92b202897406d1ac6ba3ce7c06180bd6fde4e4b6d4ff94ea19f621d17f286293d6542b2e686b726f8f116749a5b39c1333222e67293ee33270afd3a6a1ce425a0d7fdf326eb65aef1d1bb3030af0000"" width=""300"">"
4,"<img src=""https://storage.googleapis.com/cloud-samples-data/bigquery%2Ftutorials%2Fcymbal-pets%2Fimages%2Fchirpy-seed-deluxe-bird-food.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20260226%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20260226T175155Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1742492687196980&X-Goog-Signature=9358d174a6265a70eacf589d6a3b5f7d345e02715a80330c7fdf609994e48bf29249fb210749d1f253603d393f1cdaa9e1c0a7f159ecdebbc39cd0a91f4e9307100f10cdd0c10ef8af23d1c34a1800053099ab6338e2590ac9dd39abb11d48f40ee5675e2df98154292d9dfebf555cf92b4d46302f18dd7cdb758a99c22aa1fd965da08de70cf6be64b68ee2c88872cdd68628e2e82ea691e880bcaa24c9456b07fd730bf5cf7eaf71c677bfe09f54c2e3217980e0813772d7e07059c904d437296f1dfacb70f58b50b8406b13af440728e2290b852656866b26dd47dbdadf7c2ee717a645d9daca85843399316e4882d88e5ad71d23c790f6acbcfbdca7f6e0"" width=""300"">","<img src=""https://storage.googleapis.com/bigframes_blob_test/image_blur_transformed%2Fchirpy-seed-deluxe-bird-food.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20260226%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20260226T175155Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1772128421483040&X-Goog-Signature=3650f3786450b60c8a5ca722be404491cc108767f92825823794009ea4ff52b83b6cac502ed4416ad29c964ef74ef7e512d06ac3690c8251befbf87f62efb43c9229f61c02b9a3b1616abc8eaf07436671764ffc55bbd272e0270e866931bdaa9de5af3c623526da7c82abf553f8e88011d876a97a8413d7e1c0321215885e88671f1bf7a4268e839a480f8d4a3cdfd1112cffcbf224ce0baa9e5fe399679d7afa08c178d26b2531918f387cb633987c1da4660d89b41613c5681848cc29dcd2ef5a06ffc04de067a9fe0c21d6244f3cd4b7380ceb867dd46b763cb4762c58f4d6867df663b48b892aaefdcf7f2e2f6e04419611206f2ad1326bb0bcac0db6a6"" width=""300"">"

### 4. Use LLM models to ask questions and generate embeddings on images

In [9]:
from bigframes.ml import llm
gemini = llm.GeminiTextGenerator()

/usr/local/lib/python3.12/dist-packages/bigframes/core/logging/log_adapter.py:183: FutureWarning: Since upgrading the default model can cause unintended breakages, the
default model will be removed in BigFrames 3.0. Please supply an
explicit model to avoid this message.
  return method(*args, **kwargs)

In [10]:
# Ask the same question on the images
answer = gemini.predict(df_image, prompt=["what item is it?", df_image["image"]])
answer[["ml_generate_text_llm_result", "image"]]

/usr/local/lib/python3.12/dist-packages/bigframes/dtypes.py:987: JSONDtypeWarning: JSON columns will be represented as pandas.ArrowDtype(pyarrow.json_())
instead of using `db_dtypes` in the future when available in pandas
(https://github.com/pandas-dev/pandas/issues/60958) and pyarrow.
  warnings.warn(msg, bigframes.exceptions.JSONDtypeWarning)
/usr/local/lib/python3.12/dist-packages/bigframes/core/logging/log_adapter.py:229: ApiDeprecationWarning: The blob accessor is deprecated and will be removed in a future release. Use bigframes.bigquery.obj functions instead.
  return prop(*args, **kwargs)
/usr/local/lib/python3.12/dist-packages/bigframes/dtypes.py:987: JSONDtypeWarning: JSON columns will be represented as pandas.ArrowDtype(pyarrow.json_())
instead of using `db_dtypes` in the future when available in pandas
(https://github.com/pandas-dev/pandas/issues/60958) and pyarrow.
  warnings.warn(msg, bigframes.exceptions.JSONDtypeWarning)
/usr/local/lib/python3.12/dist-packages/bigframes/core/logging/log_adapter.py:229: ApiDeprecationWarning: The blob accessor is deprecated and will be removed in a future release. Use bigframes.bigquery.obj functions instead.
  return prop(*args, **kwargs)

,ml_generate_text_llm_result,image
0,The item is a tin of K9 Guard Dog Paw Balm.,"<img src=""https://storage.googleapis.com/cloud-samples-data/bigquery%2Ftutorials%2Fcymbal-pets%2Fimages%2Fk9-guard-dog-paw-balm.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20260226%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20260226T175605Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1742492703986347&X-Goog-Signature=86f5754b857cdfdaadaf1188e0717bf09d842082feb63b1f2de43a1510ebf832eeeb25666f41d5002e485aec629ea9f30b1fc7dec7fbdb930257ff62d37736b779e455e9052f759288d9a52469380cae357e8770b7eaeded419977d38557da5d057eee0723ca5be174c6460e114f7b4b451975e689dcecbde007f10187a8bb000b9d71084c52ca89480272ef2bbb1adb379f4135eae7882f9edfeb3a042025db27dcc176dd0fdf9cce1e93b68377ae15477bd4b763542729918c93a12a2b4c1832c68475efb307078e8368a79c38b8aad14ad3159719b16ea3a004757e54781dc8923092dfe600ede246be6005bd197041398d1ca078762b48f9f5c32a074525"" width=""300"">"
1,The item is a bottle of K9 Guard Dog Hot Spot Spray.,"<img src=""https://storage.googleapis.com/cloud-samples-data/bigquery%2Ftutorials%2Fcymbal-pets%2Fimages%2Fk9-guard-dog-hot-spot-spray.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20260226%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20260226T175605Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1742492702954473&X-Goog-Signature=8a909bfc1654b8c042a568841e596b14c27d7a06900b3361eefe22fec0cd4a1ab0b382c075766628a30fccc52f8fdd1dcbc0cf19318056e8f539763e67720decac4e11a2ad1c07ae77f528a2b7c6d1379892e3bf8721da32dd94eae2d4b42152f231c1cfba53f8b7b5c5fc8626d9e81a19d300486e581ccfb4bf12d219fc97a7c61ff1bd6f56878c1b8844d002078a18dd3d71b603125fbd3e9b2cdb4c1448ef2949842ce43ad87d5ecd26f01ae67181e76b5f435cddcbae4fadad6cb83fec2fc59d945bd7dbc4f1c6d301455bb13600986ddefc95d202143487ecd70ec0aa9aaf211ae8ff1566731054baadf8bf88f0b2d42245bd5da6f6b30b9a5b0c43a7fd"" width=""300"">"
2,"The image shows three bags of ""Fluffy Buns"" pet food/treats. Specifically, there's ""Timoth Hay Lend Variety Blend,"" ""Herbal Greeıs Mix Variety Blend,"" and ""Berry & Blossom Treat Blend."" There are also piles of each respective blend in front of their bags.","<img src=""https://storage.googleapis.com/cloud-samples-data/bigquery%2Ftutorials%2Fcymbal-pets%2Fimages%2Ffluffy-buns-chinchilla-food-variety-pack.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20260226%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20260226T175605Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1742492694988945&X-Goog-Signature=43bf13035c604d9a701d85ec272e94cbd7ef3aba21569e57f7128b908cc88d830d02d0da72b8387bd4139beba3c30f601639b56a855c0bc5c2210052c7e54204c69090a170efa407e7cb189071474c387a067488532e58eabc0dbeae74723b3f89fad68f6eb3ec90e69e5c3f5a1d42e9123f698e20a6163b3b00e912c52fa93ffce42bd6fbbc4e6e49e051a917e9c0dd54e8ae49a67c098aa8c4013796e5b93e42d3e34b8facc7d9e16a189773b173f9799ba7c92227d08cbae345c78ec419f3e5775080469f60228ebdf99fef02846674f720ce041b5ec7cee7ba302b03f2f9c668659ce954915d760a590baa0666b1b2a64246e555d914d2a41ed8642bcea9"" width=""300"">"
3,The item is a cat tree.,"<img src=""https://storage.googleapis.com/cloud-samples-data/bigquery%2Ftutorials%2Fcymbal-pets%2Fimages%2Fpurrfect-perch-cat-scratcher.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20260226%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20260226T175605Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1742492719670724&X-Goog-Signature=745befded412116d9a4188e33df15f87a309634eb13c152b197beffa20d7b301d641c6c5e770eeb3ab5fa7d56966a6f600765bb6225df9dd764d2e27d69d53037953d49dcc7897b7f173cc522fb5ca22f1efa172e6753a07d3b8d47850edc617a7e81888d7f2944ba3e4a50ab3b761d55475e7fe8f04bf36781b09d0fc34d9f3916a5e75fbf010519cd2524e3aeb148c69e18cadff69d2cc9dd39821214813e4fda61e1392f68057a1aa49c176bb65e8662d495c42ddd945311feba39da5a700b55b099b43aed7a19ce96dbde81e843c62a72ff093b0f9a9ad25b22ea77ea05996fae1c79d5639d8b77d7e4bff7889642a399b2d6d393bad5e507afda6e58ed7"" width=""300"">"
4,"The item is ""Chirpy Seed Deluxe Bird Food"".","<img src=""https://storage.googleapis.com/cloud-samples-data/bigquery%2Ftutorials%2Fcymbal-pets%2Fimages%2Fchirpy-seed-deluxe-bird-food.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20260226%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20260226T175605Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1742492687196980&X-Goog-Signature=7b08175c5c3acefd21876c363625262fd9ddbf43d9c86dea9671a6d404e63fc57486efe61a66b22428c8713aedea31971a01ffd26f0d3db691e065734e538ba79ba29aff082625ba24ab577f3a1cb4abff42c21036fd8fee8a8a9b3720f686243732d8b04400d8d259516254f377faee1e6dc25776c4b303aa8329234752bdb5051f39eab7671d17eb52c2718cb8aa2e10666f541512f58780b8b39439831977a1fc12750944ecaf07e1fd8aa1b5ff26f966950bbe9ccb8673460c5e74b140717e9154ac76a4d60784d3406ca75b1adeca48d355531ac55b3e05cba2e9e92581424c8394b40e72ace6bd0df87093839ff4bb165c3360aff449edf52b2d533480"" width=""300"">"

In [11]:
# Ask different questions
df_image["question"] = [
    "what item is it?",
    "what color is the picture?",
    "what is the product name?",
    "is it for pets?",
    "what is the weight of the product?",
]

In [12]:
answer_alt = gemini.predict(df_image, prompt=[df_image["question"], df_image["image"]])
answer_alt[["ml_generate_text_llm_result", "image"]]

/usr/local/lib/python3.12/dist-packages/bigframes/dtypes.py:987: JSONDtypeWarning: JSON columns will be represented as pandas.ArrowDtype(pyarrow.json_())
instead of using `db_dtypes` in the future when available in pandas
(https://github.com/pandas-dev/pandas/issues/60958) and pyarrow.
  warnings.warn(msg, bigframes.exceptions.JSONDtypeWarning)
/usr/local/lib/python3.12/dist-packages/bigframes/core/logging/log_adapter.py:229: ApiDeprecationWarning: The blob accessor is deprecated and will be removed in a future release. Use bigframes.bigquery.obj functions instead.
  return prop(*args, **kwargs)
/usr/local/lib/python3.12/dist-packages/bigframes/dtypes.py:987: JSONDtypeWarning: JSON columns will be represented as pandas.ArrowDtype(pyarrow.json_())
instead of using `db_dtypes` in the future when available in pandas
(https://github.com/pandas-dev/pandas/issues/60958) and pyarrow.
  warnings.warn(msg, bigframes.exceptions.JSONDtypeWarning)
/usr/local/lib/python3.12/dist-packages/bigframes/core/logging/log_adapter.py:229: ApiDeprecationWarning: The blob accessor is deprecated and will be removed in a future release. Use bigframes.bigquery.obj functions instead.
  return prop(*args, **kwargs)

,ml_generate_text_llm_result,image
0,The item is a container of K9Guard dog paw balm.,"<img src=""https://storage.googleapis.com/cloud-samples-data/bigquery%2Ftutorials%2Fcymbal-pets%2Fimages%2Fk9-guard-dog-paw-balm.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20260226%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20260226T175901Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1742492703986347&X-Goog-Signature=71b201e9cd37d21a31d842e9c4c9d4e46ee7964f8599cd7103202a71c4c2505e17b25a42f717e8260fda8489f47fe10bf882da01178224fed86a9379579852cf6bb87a64a2926a27ab24c61f9825d92cb98e8042b6cd3407fa33689dce442a3abef2811d91c46e6b7f8eacd374c9c46f672f05a7e824bc8bedd6ca09ca7b7ed01f3fd329428c9653b8f2776b23ee75625f4d3e41e9025b9322ece9c412c804bd26fa4ce77161c69d946fcbd2f71c3d6ddb366c036b6e0705c3a6d654f33067ff118886b0aa5e9a9f374ee0cf662ff84d280adbb152e7a7145ffad54a86ff2528bc0508908f61b88616567e8cf751d2b0e4fc1264368af08119e9c5d0c93eda60"" width=""300"">"
2,Here are the product names based on the image: * **Timoth Hay Lend Variety Plend** * **Herbal Greeıs Mix Variety Blend** * **Berry & Blossom Treat Blend**,"<img src=""https://storage.googleapis.com/cloud-samples-data/bigquery%2Ftutorials%2Fcymbal-pets%2Fimages%2Ffluffy-buns-chinchilla-food-variety-pack.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20260226%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20260226T175901Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1742492694988945&X-Goog-Signature=0a4fe5aae9e832ac89b1dd316ec32de5bf9a8f12e80370b03d9cd5bcb8e916fd261dbb84ff613194c751732eb39c7b75d67e3845007ca12be025c998ff5077db75617b7d2295a7a34939fab1dbc8ddfe8ef8f6872e8dc7b2df13b07cc1c2527515e766790c343f85b665d7b6d1c1c0009e22deb2831dfeffa6ffcad4aeb55795dee709875a4ab61a6b357106a9fb557be0e8ce19d582e3f8efe95073b726e92146419c52623374bb104f8392bc792bd5897521ae7bd37e9968f6eea2710212bc00632bfca050961f1e014edddb69a8ef70af739f0a48bd3216bf5c776343fcf60f5eece0e12e9c67851d1b1c7fd8050236b221c3e3dac3fb21daf776bf24478f"" width=""300"">"
3,"Yes, the item in the image is a cat tree, which is designed for pets, specifically cats.","<img src=""https://storage.googleapis.com/cloud-samples-data/bigquery%2Ftutorials%2Fcymbal-pets%2Fimages%2Fpurrfect-perch-cat-scratcher.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20260226%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20260226T175901Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1742492719670724&X-Goog-Signature=1929962421a9d8926991f3d8a87b2036997517b6ca9839892a11963b23f17a93f04ace3c60817ebaefa38b988d0f953afdabdb41b53e02500c12f62f89ad2305a9b80b6dc9f10ad9642182baa9cc09005542895c612b632d9f4c17d0a9b3fea92e98bb9c0543641ee01a9e571f6f6b7b65323b8d3f8bcbe937829e0b6e34b114b4bce904fc764b224cde163ddab8ffbf243ba6d74fd8fd2e3779bed00a7754b2da66a89d253d15fb32a8d45bcfdf96ab2a06edec253e420ce814a0fb09d5347100cdf2b9fbf303afb18a718ff11ad03877253d9b4919702f6321b1782470fb2cdd9f2beefd3ef8c5abdb551ceac85c120369daebdd7e87f4042c1a8d24d7fd20"" width=""300"">"
4,The net weight of the product is 15 oz (257g).,"<img src=""https://storage.googleapis.com/cloud-samples-data/bigquery%2Ftutorials%2Fcymbal-pets%2Fimages%2Fchirpy-seed-deluxe-bird-food.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20260226%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20260226T175901Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1742492687196980&X-Goog-Signature=004c19726ff2e57ee8c871ec24d96f342941ffb840130e0b46ba7b91c72ec0f03681586e934bcf6e644fddb49fb6227f7af83ff8173b3cdb0e4f32080430a09b41a5b7becc86cc040ec256837a9c7732910704d413e5e1fd76dbe2d1064abc24f6a13de712915132dbf09c25c4a833f4ceef1d6f8b4b0c429a9d89f5147d966502cae1175020099fd8c72bd5c68edca76c5c1f5390ebc08bc7416393e565c9cff5105df7bf039dd677753520670254cef4a092e9380ebca828774947997040c80709a4a842481ff22dc3547fec08a94fc46af1b460aaceb9c5dcbe2b1c38487f90ecef72efe45c0f711750524fffed88670b7ba31f5f2eff1eca2516c6a91388"" width=""300"">"
1,,"<img src=""https://storage.googleapis.com/cloud-samples-data/bigquery%2Ftutorials%2Fcymbal-pets%2Fimages%2Fk9-guard-dog-hot-spot-spray.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=bqcx-1084210331973-pcbl%40gcp-sa-bigquery-condel.iam.gserviceaccount.com%2F20260226%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20260226T175901Z&X-Goog-Expires=21600&X-Goog-SignedHeaders=host&generation=1742492702954473&X-Goog-Signature=4c800dff1bf384897177ccd912e655f92c1414e03e6fcad0752d53d583770c71280c1cdb25e3725983a93ac67354b17d1c5ccfaf0c7d2fef4c5341a3326a3ba94853af30cf7690ff8e9d8ec38d74c304669194fcd97b5e79dc1634b715352bdf180e44bef20b8d61817423e826bbe3aef422a9b0d03a7254dfa117dc35e4d1827589216fb4ef75a5d32703826a21211c0096e6d9b8eaebdbb1c812ae26505a1496f428d1e37d86031a393eb2ff3a17e5dc2884054f12297ca8394384b44969278628296dafde0c7074b6254f690f41f784866caf8adee0b156246f8448ec67266fb5019f48142645b0f2a303c9366a98e5b99cdcde95d18d92fc4a834996b25f"" width=""300"">"

In [13]:
# Generate embeddings.
embed_model = llm.MultimodalEmbeddingGenerator()
embeddings = embed_model.predict(df_image["image"])
embeddings

/usr/local/lib/python3.12/dist-packages/bigframes/core/logging/log_adapter.py:183: FutureWarning: Since upgrading the default model can cause unintended breakages, the
default model will be removed in BigFrames 3.0. Please supply an
explicit model to avoid this message.
  return method(*args, **kwargs)
/usr/local/lib/python3.12/dist-packages/bigframes/dtypes.py:987: JSONDtypeWarning: JSON columns will be represented as pandas.ArrowDtype(pyarrow.json_())
instead of using `db_dtypes` in the future when available in pandas
(https://github.com/pandas-dev/pandas/issues/60958) and pyarrow.
  warnings.warn(msg, bigframes.exceptions.JSONDtypeWarning)
/usr/local/lib/python3.12/dist-packages/bigframes/core/logging/log_adapter.py:229: ApiDeprecationWarning: The blob accessor is deprecated and will be removed in a future release. Use bigframes.bigquery.obj functions instead.
  return prop(*args, **kwargs)
/usr/local/lib/python3.12/dist-packages/bigframes/dtypes.py:987: JSONDtypeWarning: JSON columns will be represented as pandas.ArrowDtype(pyarrow.json_())
instead of using `db_dtypes` in the future when available in pandas
(https://github.com/pandas-dev/pandas/issues/60958) and pyarrow.
  warnings.warn(msg, bigframes.exceptions.JSONDtypeWarning)

,ml_generate_embedding_result,ml_generate_embedding_status,ml_generate_embedding_start_sec,ml_generate_embedding_end_sec,content
0,[ 0.00638626 0.01666436 0.00452246 ... -0.02...,,<NA>,<NA>,"{""access_urls"":{""expiry_time"":""2026-02-26T23:5..."
1,[ 0.00973689 0.02148374 0.00244311 ... 0.00...,,<NA>,<NA>,"{""access_urls"":{""expiry_time"":""2026-02-26T23:5..."
2,[ 0.01197349 0.02138474 0.05967783 ... -0.01...,,<NA>,<NA>,"{""access_urls"":{""expiry_time"":""2026-02-26T23:5..."
3,[-0.02621164 0.02797646 0.04416909 ... -0.01...,,<NA>,<NA>,"{""access_urls"":{""expiry_time"":""2026-02-26T23:5..."
4,[ 0.05918641 0.01251377 0.01907265 ... 0.01...,,<NA>,<NA>,"{""access_urls"":{""expiry_time"":""2026-02-26T23:5..."

### 5. PDF extraction and chunking function

This section demonstrates how to extract text and chunk text from PDF files using custom BigQuery Python UDFs and the `pypdf` library.

In [14]:
# Construct the canonical connection ID
FULL_CONNECTION_ID = f"{PROJECT}.{LOCATION}.bigframes-default-connection"

@bpd.udf(
    input_types=[str],
    output_type=str,
    dataset=DATASET_ID,
    name="pdf_extract",
    bigquery_connection=FULL_CONNECTION_ID,
    packages=["pypdf", "requests", "cryptography"],
)
def pdf_extract(src_obj_ref_rt: str) -> str:
    import io
    import json
    from pypdf import PdfReader
    import requests
    src_obj_ref_rt_json = json.loads(src_obj_ref_rt)
    src_url = src_obj_ref_rt_json["access_urls"]["read_url"]
    response = requests.get(src_url, timeout=30, stream=True)
    response.raise_for_status()
    pdf_bytes = response.content
    pdf_file = io.BytesIO(pdf_bytes)
    reader = PdfReader(pdf_file, strict=False)
    all_text = ""
    for page in reader.pages:
        page_extract_text = page.extract_text()
        if page_extract_text:
            all_text += page_extract_text
    return all_text

@bpd.udf(
    input_types=[str, int, int],
    output_type=list[str],
    dataset=DATASET_ID,
    name="pdf_chunk",
    bigquery_connection=FULL_CONNECTION_ID,
    packages=["pypdf", "requests", "cryptography"],
)
def pdf_chunk(src_obj_ref_rt: str, chunk_size: int, overlap_size: int) -> list[str]:
    import io
    import json
    from pypdf import PdfReader
    import requests
    src_obj_ref_rt_json = json.loads(src_obj_ref_rt)
    src_url = src_obj_ref_rt_json["access_urls"]["read_url"]
    response = requests.get(src_url, timeout=30, stream=True)
    response.raise_for_status()
    pdf_bytes = response.content
    pdf_file = io.BytesIO(pdf_bytes)
    reader = PdfReader(pdf_file, strict=False)
    all_text_chunks = []
    curr_chunk = ""
    for page in reader.pages:
        page_text = page.extract_text()
        if page_text:
            curr_chunk += page_text
            while len(curr_chunk) >= chunk_size:
                split_idx = curr_chunk.rfind(" ", 0, chunk_size)
                if split_idx == -1:
                    split_idx = chunk_size
                actual_chunk = curr_chunk[:split_idx]
                all_text_chunks.append(actual_chunk)
                overlap = curr_chunk[split_idx + 1 : split_idx + 1 + overlap_size]
                curr_chunk = overlap + curr_chunk[split_idx + 1 + overlap_size :]
    if curr_chunk:
        all_text_chunks.append(curr_chunk)
    return all_text_chunks

/usr/local/lib/python3.12/dist-packages/bigframes/pandas/__init__.py:151: PreviewWarning: udf is in preview.
  return global_session.with_default_session(

In [15]:
df_pdf = bpd.from_glob_path("gs://cloud-samples-data/bigquery/tutorials/cymbal-pets/documents/*", name="pdf")

# Generate a JSON string containing the runtime information (including signed read URLs)
access_urls = get_runtime_json_str(df_pdf["pdf"], mode="R")

# Apply PDF extraction
df_pdf["extracted_text"] = access_urls.apply(pdf_extract)

# Apply PDF chunking
df_pdf["chunked"] = access_urls.apply(pdf_chunk, args=(2000, 200))

df_pdf[["extracted_text", "chunked"]]

,extracted_text,chunked
0,CritterCuisine Pro 5000 - Automatic Pet Feeder...,"[""CritterCuisine Pro 5000 - Automatic Pet Feed..."

In [16]:
# Explode the chunks to see each chunk as a separate row
chunked = df_pdf["chunked"].explode()
chunked

0    CritterCuisine Pro 5000 - Automatic Pet Feeder...
0    on a level, stable surface to prevent tipping....
0    included)
to maintain the schedule during powe...
0    digits for Meal 1 will flash.
 . Use the UP/DO...
0    paperclip) for 5
seconds. This will reset all ...
0    unit with a damp cloth. Do not immerse the bas...
0    continues,
contact customer support.
E2: Food ...
Name: chunked, dtype: string

### 6. Audio transcribe

In [17]:
audio_gcs_path = "gs://bigframes_blob_test/audio/*"
df = bpd.from_glob_path(audio_gcs_path, name="audio")

In [18]:
# The audio_transcribe function is a convenience wrapper around bigframes.bigquery.ai.generate.
# Here's how to perform the same operation directly:

audio_series = df["audio"]
prompt_text = (
    "**Task:** Transcribe the provided audio. **Instructions:** - Your response "
    "must contain only the verbatim transcription of the audio. - Do not include "
    "any introductory text, summaries, or conversational filler in your response. "
    "The output should begin directly with the first word of the audio."
)

# Convert the audio series to the runtime representation required by the model.
# This involves fetching metadata and getting a signed access URL.
audio_metadata = bbq.obj.fetch_metadata(audio_series)
audio_runtime = bbq.obj.get_access_url(audio_metadata, mode="R")

transcribed_results = bbq.ai.generate(
    prompt=(prompt_text, audio_runtime),
    endpoint="gemini-2.0-flash-001",
    model_params={"generationConfig": {"temperature": 0.0}},
)

transcribed_series = transcribed_results.struct.field("result").rename("transcribed_content")
transcribed_series

/usr/local/lib/python3.12/dist-packages/bigframes/dtypes.py:987: JSONDtypeWarning: JSON columns will be represented as pandas.ArrowDtype(pyarrow.json_())
instead of using `db_dtypes` in the future when available in pandas
(https://github.com/pandas-dev/pandas/issues/60958) and pyarrow.
  warnings.warn(msg, bigframes.exceptions.JSONDtypeWarning)

0    Now, as all books, not primarily intended as p...
Name: transcribed_content, dtype: string

In [19]:
# To get verbose results (including status), we can extract both fields from the result struct.
transcribed_content_series = transcribed_results.struct.field("result")
transcribed_status_series = transcribed_results.struct.field("status")

transcribed_series_verbose = bpd.DataFrame(
    {
        "status": transcribed_status_series,
        "content": transcribed_content_series,
    }
)
# Package as a struct for consistent display
transcribed_series_verbose = bbq.struct(transcribed_series_verbose).rename("transcription_results")
transcribed_series_verbose

0    {'status': '', 'content': 'Now, as all books, ...
Name: transcription_results, dtype: struct<status: string, content: string>[pyarrow]

### 7. Extract EXIF metadata from images

This section demonstrates how to extract EXIF metadata from images using a custom BigQuery Python UDF and the `Pillow` library.

In [20]:
# Construct the canonical connection ID
FULL_CONNECTION_ID = f"{PROJECT}.{LOCATION}.bigframes-default-connection"

@bpd.udf(
    input_types=[str],
    output_type=str,
    dataset=DATASET_ID,
    name="extract_exif",
    bigquery_connection=FULL_CONNECTION_ID,
    packages=["pillow", "requests"],
    max_batching_rows=8192,
    container_cpu=0.33,
    container_memory="512Mi"
)
def extract_exif(src_obj_ref_rt: str) -> str:
    import io
    import json
    from PIL import ExifTags, Image
    import requests
    src_obj_ref_rt_json = json.loads(src_obj_ref_rt)
    src_url = src_obj_ref_rt_json["access_urls"]["read_url"]
    response = requests.get(src_url, timeout=30)
    bts = response.content
    image = Image.open(io.BytesIO(bts))
    exif_data = image.getexif()
    exif_dict = {}
    if exif_data:
        for tag, value in exif_data.items():
            tag_name = ExifTags.TAGS.get(tag, tag)
            exif_dict[tag_name] = value
    return json.dumps(exif_dict)

/usr/local/lib/python3.12/dist-packages/bigframes/pandas/__init__.py:151: PreviewWarning: udf is in preview.
  return global_session.with_default_session(

In [21]:
# Create a Multimodal DataFrame from the sample image URIs
exif_image_df = bpd.from_glob_path(
    "gs://bigframes_blob_test/images_exif/*",
    name="blob_col",
)

# Generate a JSON string containing the runtime information (including signed read URLs)
# This allows the UDF to download the images from Google Cloud Storage
access_urls = get_runtime_json_str(exif_image_df["blob_col"], mode="R")

# Apply the BigQuery Python UDF to the runtime JSON strings
# We cast to string to ensure the input matches the UDF's signature
exif_json = access_urls.astype(str).apply(extract_exif)

# Parse the resulting JSON strings back into a structured JSON type for easier access
exif_data = bbq.parse_json(exif_json)

exif_data

/usr/local/lib/python3.12/dist-packages/bigframes/core/utils.py:228: PreviewWarning: The JSON-related API `parse_json` is in preview. Its behavior may
change in future versions.
  warnings.warn(bfe.format_message(msg), category=bfe.PreviewWarning)

0    {"ExifOffset":47,"Make":"MyCamera"}
Name: blob_col, dtype: extension<dbjson<JSONArrowType>>[pyarrow]